### ISSUE TITLE
Run js or xsl based on processing instruction

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker#183]
Determine the Macmillan template version number from the processing instruction, and then run the js for all MS past a certain version, and xsl for all others or if no version PI is present.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Since it looks like we'll be able to pull the template version directly from the document's xml (yay!), a pi may not be necessary. However, for html files: we should come up with a method to specify template version or otherwise flag a file to run via section start styles (a meta tag?). We may want to write that in all html files once we capture it from the xml as well..  https://app.asana.com/0/142682204252343/142682204252343 does this sound like the right path?

**Comment by MacmillanWorkflows** [comment]
➤ Nellie McKesson commented:

Here's what I had in mind:

In bookmaker/htmlmaker:
* Get the version number from the XML, making sure to do this as a conditional, so that if the version field does not exist, we won't have a failure. I'm fine with doing this via either ruby or python, but would like to avoid using any powershell or other platform-specific processes.
* Add any found version number to the HTML as a "meta" tag
* Add a new method to run the new javascripts
* Add a conditional to do the following:
IF version_number exists and is greater than or equal to the SS version THEN Run new javascripts method
ELSE Run the existing convertdocxtoxml and convertxmltohtml methods.

In bookmaker_addons/metadata_preprocessing:
* Add a conditional to add the version number to the config.json

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

This is included in these PRs:
https://github.com/macmillanpublishers/bookmaker/pull/185
https://github.com/macmillanpublishers/bookmaker_addons/pull/158

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

merged into sectionstartstaging branches
