### ISSUE TITLE
epubmaker failing if no cover file provided in torDOTcom_firstpass

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker#82]
epubmaker failing on line 73: `covercontents = File.read("#{OEBPS_dir}/cover.html")`
error: `No such file or directory - S:/bookmaker_tmp/TheBalladofBlackTomfinalmsforBookmaker/OEBPS/cover.html `

This causes epubmaker to repeat in a loop.

This is failing on torDOTcom_firstpass, which should not require a cover file from the user because it uses covermaker. Covermaker produces `pass` for `The cover jpg was successfully created`, so something is failing in the conversion to cover.html

**Comment by nelliemckesson** [comment]
Fixed - this was caused by an earlier change to the metadata_preprocessing script that looked for existing cover files and then presupplied the cover file name based on what it found, falling back to "Unknown" if no file was found. Revised so that for firstpass and egalley conversions, if no cover file is found, metadata will fall back to use ISBN_FC.jpg as the cover filename.
