### ISSUE TITLE
TOC duplicated in PDF

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker#89]
See attached PDF -- both the Bookmaker-created TOC and the TOC as it appears in the Word doc are in the final PDF.
[9781250055774_POD.pdf](https://github.com/macmillanpublishers/bookmaker/files/41802/9781250055774_POD.pdf)

**Comment by ericawarren** [comment]
Oh also this is in the bookmaker_picador / picador_arc-serif path

**Comment by nelliemckesson** [comment]
Bookmaker was set to suppress manually-created TOCs, however it requires the TOC to start with a heading that contains the word "Contents", in titlecase. I've added more fine-tuned handling for TOCs so that users can choose to use either the automatically-generated TOC or one that they've created manually. They can switch either TOC on or off via the oneoff CSS.
